apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: forklift-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: The Konveyor Forklift Operator fully manages the deployment and life
    cycle of Forklift on OpenShift.
  displayName: Konveyor Forklift Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - migration
  links:
  - name: Forklift Operator
    url: https://forklift-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
    url: https://github.com/konveyor/forklift-operator
  version: 0.0.0
