- hosts: localhost
  gather_facts: false
  vars:
    new_release: ""
    old_release: ""
  tasks:
  - assert:
      that:
        - new_release != ''
        - old_release != ''
      fail_msg: "new_release and old_release must be provided and must follow semver convention (i.e 2.0.0)"

  - name: "Add new bundle to old index image"
    shell: |
           opm index add -c podman -f quay.io/konveyor/forklift-operator-index:release-v{{ old_release }} \
           --bundles quay.io/konveyor/forklift-operator-bundle:release-v{{ new_release }} \
           --tag quay.io/konveyor/forklift-operator-index:release-v{{ new_release }}

  - name: "Push updated index as a new image"
    shell: podman push quay.io/konveyor/forklift-operator-index:release-v{{ new_release }}

  - name: "Add development bundle to the new index"
    shell: |
           opm index add -c podman -f quay.io/konveyor/forklift-operator-index:release-v{{ new_release }} \
           --bundles quay.io/konveyor/forklift-operator-bundle:latest \
           --tag quay.io/konveyor/forklift-operator-index:latest

  - name: "Push the complete index to latest"
    shell: podman push quay.io/konveyor/forklift-operator-index:latest
